### ISSUE TITLE
Error after insatlling the plugin

### ISSUE THREAD

**Issue by ramiy** [infogram/infogram-wordpress#5]
Re-create:

1. Go to "Plugins" -> "Add New".
2. Search the "Infogr.am" plugin.
3. Installed the plugin.
4. Go to "Settings" -> "Infogr.am Settings".

The result is:
![Infogr.am settings error message](http://i.imgur.com/e4M74Kz.png)

I just installed the plugin, already an error message?

**Comment by torbjon** [comment]
#fixed

![screen shot 2016-02-04 at 17 02 54](https://cloud.githubusercontent.com/assets/49188/12818897/617a510a-cb61-11e5-93e9-cdeb3ea06a4d.png)
