### ISSUE TITLE
Plugin makes excessive calls back home, doubling admin server load time

### ISSUE THREAD

**Issue by MickeyKay** [infogram/infogram-wordpress#6]
Hi there,

First of all, great plugin. Love it! Works like a charm.

That said, I've come across an issue that seems somewhat significant. In simple terms, after installing the Infogram plugin, we saw an immediate jump in our admin-side server transaction time:

![image](https://cloud.githubusercontent.com/assets/3189678/17043289/329d9076-4f6a-11e6-9bd9-1cbfad71ee5c.png)

![image](https://cloud.githubusercontent.com/assets/3189678/17043423/5db0617a-4f6b-11e6-8ab2-47aa85592849.png)

Digging in a bit further, I noticed that you're making an external request on every single admin page load.

* The chain gets triggered on the `plugins_loaded` action hook when you call `infogr_create_object()`. 
* This in turn calls the `check_settings()` method of the `Infogram` class, which in turn calls the `send_request()` method.
* This makes an external request out to the Infogram API.

All in all, this means that your plugin is making an external request on every single admin page load, and as you can see in the charts above, this accounts for a significant, synchronous delay in the server response.

Is there a reason you need to make this call on every page load? Can't you cache the response for a fixed amount of time? This would improve overall admin response times tremendously. You could even provide an admin button/link to clear the response cache if need be, to ensure updates made on the Infogram backend are reflected within WordPress.

Alternately, you could async this external call via Ajax, which would also solve the problem and at least not block rendering of the admin page.

Either way, please let me know how you hope to resolve this issue, and/or if there's any way that I can be of assistance.

Thanks!
Mickey

**Comment by torbjon** [comment]
@MickeyKay thanks for research and feedback

can you please check this update https://github.com/infogram/infogram-wordpress/pull/7 ?

**Comment by MickeyKay** [comment]
Just reviewed this. Looks great! Thanks so much for jumping on this. I did
leave a few comments you may want to address before merging. Thanks again!
Please let me know once this update is ready to go so we can implement and
test.

**Comment by torbjon** [comment]
thanks again, updated, merged and released
