### ISSUE TITLE
Fatal error after WordPress 4.6 update

### ISSUE THREAD

**Issue by iMicknl** [infogram/infogram-wordpress#9]
Infogram includes a Requests class and also an older version of this package. (http://github.com/rmccue/Requests). The Request_Response class is missing the is_redirect() function, which causes a fatal error on every HTTP request. (which is done the right way, through the WordPress functions).

`Fatal error: Call to undefined method Requests_Response::is_redirect()`

I wonder why is chosen to use another library for requests, instead of the builtin WordPress methods? In that way this issue could have never happened and it is more according the WordPress developer guidelines.

If I have time; I will make a PR, but this shouldn't be that hard to fix.

**Comment by torbjon** [comment]
master update, @iMicknl please check

**Comment by iMicknl** [comment]
Thanks for the quick response. I will checkout master asap.

I understand that this is the fastest way to fix it for now, but I would suggest making use of the WordPress core functions, instead of including the library in the plugin.

**Comment by MickeyKay** [comment]
Any update on this one? We're looking to update as well. Thanks!

**Comment by aicis001** [comment]
@MickeyKay you can download the latest version of plugin from GitHub. The last version in wordpress plugins will be today or tomorrow.
